// All UI strings in Bahasa Indonesia
export const Strings = {
  // App
  appName: 'PadiBot',
  tagline: 'Tanam Cerdas, Panen Lebih',

  // Navigation tabs
  tabDashboard: 'Beranda',
  tabFields: 'Sawah',
  tabHistory: 'Riwayat',
  tabSettings: 'Pengaturan',

  // Dashboard
  dashboardWelcome: 'Selamat Datang',
  dashboardMachineSection: 'Status Mesin',
  dashboardFieldSection: 'Sawah Aktif',
  dashboardLastMission: 'Misi Terakhir',
  dashboardStartMission: '🌾  Mulai Misi Baru',
  dashboardManualControl: '🕹️  Kontrol Manual',
  dashboardHistory: '📊  Riwayat Misi',
  dashboardNoField: 'Belum ada sawah dipilih',
  dashboardSelectField: 'Pilih Sawah',
  dashboardChangeField: 'Ganti Sawah',
  dashboardNoMission: 'Belum ada riwayat misi',

  // Field
  fieldListTitle: 'Daftar Sawah',
  fieldListEmpty: 'Belum Ada Sawah',
  fieldListEmptyDesc: 'Tambahkan sawah pertama Anda untuk mulai membuat misi tanam',
  fieldAddButton: '+ Tambah Sawah',
  fieldSearch: 'Cari sawah...',
  fieldCreateTitle: 'Tambah Sawah Baru',
  fieldEditTitle: 'Edit Sawah',
  fieldNameLabel: 'Nama Sawah',
  fieldNamePlaceholder: 'Contoh: Sawah Utama',
  fieldBoundaryLabel: 'Titik Batas Sawah',
  fieldBoundaryHint: 'Masukkan minimal 3 titik batas sawah',
  fieldAddPoint: '+ Tambah Titik Manual',
  fieldPointPrefix: 'Titik',
  fieldAreaLabel: 'Luas',
  fieldPerimeterLabel: 'Keliling',
  fieldSave: 'Simpan',
  fieldCancel: 'Batal',
  fieldDelete: 'Hapus',
  fieldDeleteConfirmTitle: 'Hapus Sawah?',
  fieldDeleteConfirmBody: (name: string) =>
    `Sawah "${name}" dan semua riwayat misinya akan dihapus permanen.`,
  fieldStartMission: 'Misi Baru',

  // Planting settings
  plantingSettingsTitle: 'Pengaturan Tanam',
  plantingFieldLabel: 'Sawah yang Dipilih',
  plantingWidthLabel: 'Lebar Kerja Mesin (meter)',
  plantingWidthHint: 'Biasanya 1.2 – 2.0 meter',
  plantingHeadlandLabel: 'Lebar Headland (meter)',
  plantingHeadlandHint: 'Area untuk mesin berputar di ujung jalur',
  plantingOrientationLabel: 'Orientasi Jalur',
  plantingOrientationHint: (deg: number) => `${deg}° dari utara`,
  plantingEstimate: 'Estimasi',
  plantingLanes: 'jalur',
  plantingDistance: 'jarak total',
  plantingCoverage: 'cakupan',
  plantingGenerate: 'Generate Jalur →',
  plantingGenerating: 'Membuat jalur...',

  // Route preview
  routePreviewTitle: 'Preview Jalur',
  routeApprove: '✓ Approve & Lanjutkan →',
  routeEdit: '← Ubah Pengaturan',
  routeLanesLabel: 'Jalur',
  routeDistanceLabel: 'Jarak',
  routeCoverageLabel: 'Cakupan',

  // Mission execution
  missionTitle: 'Eksekusi Misi',
  missionStart: '▶  MULAI MISI',
  missionPause: '⏸  PAUSE',
  missionResume: '▶  LANJUTKAN',
  missionStop: '■  STOP',
  missionEmergencyStop: '⛔  BERHENTI DARURAT',
  missionProgress: (pct: number) => `${pct}% Selesai`,
  missionLane: (cur: number, total: number) => `Jalur ${cur}/${total}`,
  missionStopConfirmTitle: 'Hentikan Misi?',
  missionStopConfirmBody: 'Misi akan dihentikan. Mesin akan berhenti di posisi saat ini.',
  missionStopConfirmCancel: 'Lanjutkan Misi',
  missionStopConfirmOk: 'Hentikan',
  missionEmergencyConfirmTitle: '⚠️  Berhenti Darurat?',
  missionEmergencyConfirmBody: 'Mesin akan segera berhenti.',
  missionEmergencyConfirmCancel: 'Batalkan',
  missionEmergencyConfirmOk: 'YA, BERHENTI',
  missionCompleteTitle: '✅  Misi Selesai!',
  missionViewReport: 'Lihat Laporan',
  missionBackHome: 'Kembali ke Beranda',
  missionExitConfirmTitle: 'Misi Masih Berjalan',
  missionExitConfirmBody: 'Keluar dari layar ini tidak akan menghentikan misi. Lanjutkan?',

  // Manual control
  manualControlTitle: 'Kontrol Manual',
  manualWarning: '⚠️  Mode kontrol manual — harap perhatikan lingkungan sekitar',
  manualForward: 'MAJU',
  manualBackward: 'MUNDUR',
  manualLeft: 'KIRI',
  manualRight: 'KANAN',
  manualStop: 'STOP',
  manualSpeedLabel: 'Kecepatan',
  manualSpeedSlow: 'Lambat',
  manualSpeedMedium: 'Sedang',
  manualSpeedFast: 'Cepat',

  // History
  historyTitle: 'Riwayat Misi',
  historyEmpty: 'Belum Ada Riwayat Misi',
  historyEmptyDesc: 'Riwayat misi Anda akan muncul di sini setelah misi selesai',
  historyFilterAll: 'Semua',
  historyFilterCompleted: 'Selesai',
  historyFilterStopped: 'Dihentikan',
  historyFilterError: 'Error',

  // Mission detail
  missionDetailTitle: 'Detail Misi',
  missionDetailCoverage: 'Cakupan',
  missionDetailArea: 'Area Tertanam',
  missionDetailDistance: 'Jarak Total',
  missionDetailLanes: 'Jalur Selesai',
  missionDetailLog: 'Log Misi',
  missionDetailExport: '↗  Ekspor Laporan',

  // Settings
  settingsTitle: 'Pengaturan',
  settingsConnectionSection: 'Koneksi Arduino',
  settingsConnectionType: 'Tipe Koneksi',
  settingsWifiIp: 'IP Address',
  settingsWifiPort: 'Port',
  settingsWifiTest: '● Test Koneksi WiFi',
  settingsBtScan: 'Scan Bluetooth',
  settingsBtRescan: '🔄  Scan Ulang Perangkat',
  settingsBtAndroidOnly: 'Bluetooth hanya tersedia di app Android',
  settingsGsmBroker: 'MQTT Broker',
  settingsGsmDeviceId: 'Device ID',
  settingsGsmUsername: 'Username (opsional)',
  settingsGsmPassword: 'Password (opsional)',
  settingsGsmTest: '● Test Koneksi MQTT',
  settingsMachineSection: 'Default Mesin (Arduino)',
  settingsDefaultWidth: 'Lebar Kerja Default',
  settingsDefaultHeadland: 'Lebar Headland Default',
  settingsDefaultSpeed: 'Kecepatan Max',
  settingsAppSection: 'Aplikasi',
  settingsDebugMode: 'Mode Debug',
  settingsDataSection: 'Data',
  settingsClearData: 'Hapus Semua Data',
  settingsClearDataConfirmTitle: 'Hapus Semua Data?',
  settingsClearDataConfirmBody: 'Semua data sawah, misi, dan riwayat akan dihapus permanen.',
  settingsAboutSection: 'Tentang',
  settingsVersion: 'Versi',
  settingsGithub: 'GitHub',

  // Machine status
  machineConnected: 'Terhubung',
  machineConnecting: 'Menghubungkan...',
  machineDisconnected: 'Terputus',
  machineSimulator: 'Simulator Aktif',
  machineError: 'Error Koneksi',

  // Mission status labels
  statusDraft: 'Draft',
  statusReady: 'Siap',
  statusRunning: 'Berjalan',
  statusPaused: 'Dijeda',
  statusCompleted: 'Selesai',
  statusStopped: 'Dihentikan',
  statusError: 'Error',

  // GPS status
  gpsGood: 'Fix',
  gpsDgps: 'DGPS',
  gpsFloat: 'Float',
  gpsNone: 'Tidak Ada',
  gpsRtk: 'RTK',

  // Telemetry labels
  telemetryBattery: 'Baterai',
  telemetryGps: 'GPS',
  telemetrySpeed: 'Kecepatan',
  telemetryLane: 'Jalur',

  // Units
  unitMeter: 'm',
  unitMeterSquared: 'm²',
  unitMeterPerSecond: 'm/s',
  unitPercent: '%',
  unitDegree: '°',

  // General
  save: 'Simpan',
  cancel: 'Batal',
  delete: 'Hapus',
  confirm: 'Konfirmasi',
  close: 'Tutup',
  back: 'Kembali',
  next: 'Lanjutkan',
  loading: 'Memuat...',
  processing: 'Memproses...',
  retry: 'Coba Lagi',
  ok: 'OK',

  // Error messages
  errorGeneral: 'Terjadi kesalahan. Coba lagi.',
  errorSave: 'Gagal menyimpan data',
  errorLoad: 'Gagal memuat data — Coba refresh',
  errorFieldMinPoints: 'Minimal 3 titik batas sawah',
  errorFieldMinArea: 'Luas sawah terlalu kecil (min. 100 m²)',
  errorFieldName: 'Nama sawah wajib diisi',
  errorMachineWidth: 'Lebar kerja harus antara 0.5 – 5.0 m',
  errorHeadlandWidth: 'Lebar headland harus antara 1.0 – 10.0 m',
  errorRouteGeneration: 'Jalur tidak dapat dibuat dengan parameter ini',
  errorConnectionFailed: 'Gagal terhubung ke mesin',
  errorMissionStart: 'Gagal memulai misi',

  // Success messages
  successFieldSaved: '✓ Sawah berhasil disimpan',
  successFieldDeleted: '✓ Sawah berhasil dihapus',
  successMissionSaved: '✓ Misi berhasil disimpan',
  successConnected: '✓ Berhasil terhubung',
} as const;
